version: "3"
services:
  #Servidor Grafana
  grafana:
    build:
      context: $PWD/dockerGrafana/
      dockerfile: Dockerfile
    container_name: grafana.server
    hostname: grafana.server
    ports:
      - "3000:3000"
    volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data (chown 472:472 /srv/docker/grafana/data)
      - /srv/docker/grafana/data:/usr/share/grafana/data
    networks:
      _net:
       ipv4_address: 172.41.0.2
  #Servidor InfluxDB
  influxdb:
    build:      
      context: $PWD/dockerInfluxDB/
      dockerfile: Dockerfile
    container_name: influxdb.server
    hostname: influxdb.server
    ports: 
      - "8086:8086"
      - "8088:8088"
    volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb
    networks:
      _net:
       ipv4_address: 172.41.0.3
  #Telegraf
  telegraf:
   image: telegraf
   container_name: telegraf
   hostname: telegraf
   restart: always
   extra_hosts:
     - "influxdb:172.41.0.3"
     - "openldap:172.41.0.5"
     - "www.virtual.com:172.41.0.6"
   environment:
     HOST_PROC: /rootfs/proc
     HOST_SYS: /rootfs/sys
     HOST_ETC: /rootfs/etc
   volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys:/rootfs/sys:ro
    - /proc:/rootfs/proc:ro
    - /etc:/rootfs/etc:ro
   networks:
     _net:
       ipv4_address: 172.41.0.4
  #Servidor OpenLDAP
  ldap:
   build:      
      context: $PWD/LDAPmonitoring/
      dockerfile: Dockerfile
   container_name: ldap.server
   hostname: ldap.server
   ports: 
     - "389:389"
   networks:
     _net:
       ipv4_address: 172.41.0.5
  #Servidor HTTP
  httpd:
   build:
      context: $PWD/HTTPmonitoring/
      dockerfile: Dockerfile
   container_name: www.myserver.org
   hostname: www.myserver.org
   ports: 
     - "80:80"
   networks:
     _net:
       ipv4_address: 172.41.0.6
   
networks:
  _net:
   driver: bridge
   ipam:
    config:
      - subnet: 172.41.0.0/16
