version: "3"
services:
  #Servidor Grafana
  grafana:
    build:
      context: $PWD/dockerGrafana/
      dockerfile: Dockerfile
    container_name: grafana.server
    hostname: grafana.server
    ports:
      - "3000:3000"
    volumes:
    # Data persistency
      - "grafana_data:/usr/share/grafana/data"
    networks:
      _net:
       ipv4_address: 172.41.0.2
  #Servidor InfluxDB
  influxdb:
    build:      
      context: $PWD/dockerInfluxDB/
      dockerfile: Dockerfile
    container_name: influxdb.server
    hostname: influxdb.server
    ports: 
      - "8086:8086"
      - "8088:8088"
    volumes:
    # Data persistency
      - "influxdb_data:/var/lib/influxdb"
    networks:
      _net:
       ipv4_address: 172.41.0.3
       
volumes:
  grafana_data:
  influxdb_data:
networks:
  _net:
   driver: bridge
   ipam:
    config:
      - subnet: 172.41.0.0/16
